### ISSUE TITLE
Python command for Iris example won't run (Pandas not found), no commit created

### ISSUE THREAD

**Issue by dkp** [datalad/datalad-binder#5]
datalad run -m "analyze iris data with classification analysis" \
--input "input/iris.csv" \
--output "prediction_report.csv" \
--output "pairwise_relationships.png" \
"python3 code/script.py"

[INFO   ] Making sure inputs are available (this may take some time) 
get(ok): input/iris.csv (file) [from web...]    
[INFO   ] == Command start (output follows) ===== 
Traceback (most recent call last):
  File "code/script.py", line 2, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[INFO   ] == Command exit (modification check follows) ===== 
[INFO   ] The command had a non-zero exit code. If this is expected, you can save the changes with 'datalad save -d . -r -F .git/COMMIT_EDITMSG' 
CommandError: 'python3 code/script.py' failed with exitcode 1 under /home/jovyan/tutorials/notebooks/paper-remodnav/remodnav/myanalysis

**Comment by jsheunis** [comment]
Hi @dkp, thanks for logging the issue! I was able to reproduce this on my side too (using the the *Explore DataLad - an intro* Binder instance, available from this repo: https://github.com/datalad/tutorials.). There are two possible fixes for this:

- update the `datalad-binder` repo (specifically the [environment.yml](https://github.com/datalad/datalad-binder/blob/main/environment.yml) file) to include the required packages (`pandas`, `seaborn`, `scikit-learn`)
- update the tutorial notebook itself to install the packages with pip.

I think option 2 is the better option because the packages are specific to this particular tutorial, and installing them in the binder instance would make them (unnecessarily) available for all notebooks using the `datalad-binder` setup.

If you're interested, you're welcome to create a PR to add these few lines to the tutorial. notebook. But definitely no problem if not :)

**Comment by jsheunis** [comment]
We went for option 1: https://github.com/datalad/datalad-binder/commit/65e0d62b78e7e5c988467e1d865f6af3d084dbfc
